# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: filedl.proto for package 'filedl'

require 'grpc'
require 'filedl_pb'

module Filedl
  module FileService
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'filedl.FileService'

      rpc :Download, FileRequest, stream(FileResponse)
    end

    Stub = Service.rpc_stub_class
  end
end
