# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: filedl.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("filedl.proto", :syntax => :proto3) do
    add_message "filedl.FileRequest" do
      optional :name, :string, 1
    end
    add_message "filedl.FileResponse" do
      optional :data, :bytes, 1
    end
  end
end

module Filedl
  FileRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("filedl.FileRequest").msgclass
  FileResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("filedl.FileResponse").msgclass
end
